# Generated by Django 4.2.7 on 2025-02-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="account",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="admission_fee_receipt_no",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="admission_fees",
        ),
        migrations.RemoveField(
            model_name="historicaladmission",
            name="account",
        ),
        migrations.RemoveField(
            model_name="historicaladmission",
            name="admission_fee_receipt_no",
        ),
        migrations.RemoveField(
            model_name="historicaladmission",
            name="admission_fees",
        ),
    ]
