# Generated by Django 4.2.7 on 2025-02-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        ("admission", "0002_remove_admission_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.course",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladmission",
            name="course",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="web.course",
            ),
        ),
    ]
