# Generated by Django 5.0.1 on 2025-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_admission_branch_historicaladmission_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicaladmission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
