# Generated by Django 5.0.1 on 2025-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0003_alter_admission_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="is_active",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                verbose_name="Mark as Active",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladmission",
            name="is_active",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                verbose_name="Mark as Active",
            ),
        ),
    ]
