# Generated by Django 4.2.7 on 2025-02-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("admission", "0003_alter_admission_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbatch",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="branches.branch",
            ),
        ),
    ]
