# Generated by Django 5.0.1 on 2025-02-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0004_alter_admission_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="course",
        ),
        migrations.RemoveField(
            model_name="historicaladmission",
            name="course",
        ),
    ]
