# Generated by Django 4.2.7 on 2025-02-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("admission", "0004_batch_branch_historicalbatch_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
        ),
    ]
