# Generated by Django 5.0.1 on 2025-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0005_remove_admission_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalbatch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
