# Generated by Django 5.0.1 on 2024-03-12 18:42

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_head", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="banner")),
                ("title", models.CharField(max_length=500)),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("date", models.DateField()),
                ("person_name", models.CharField(max_length=50)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="blog/", verbose_name="Blog"
                    ),
                ),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("branch_name", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("location", models.TextField()),
                ("phone_number", models.CharField(max_length=100)),
                ("whatsapp_number", models.CharField(max_length=100)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="branch/"),
                ),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "about_branch",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="About Branch"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Branches",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("branch", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("position", models.CharField(max_length=128, null=True)),
                ("message", models.TextField()),
                ("resume", models.FileField(max_length=500, upload_to="resume")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="course/", verbose_name="Course"
                    ),
                ),
                ("details", models.TextField()),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("seat", models.IntegerField()),
                ("duration", models.CharField(max_length=10)),
                ("fees", models.CharField(max_length=50)),
                (
                    "syllabus",
                    models.FileField(blank=True, null=True, upload_to="syllabus"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=128)),
                ("media", models.FileField(max_length=500, upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("venue", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="freecourse/"
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("details", models.TextField()),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="instructor/", verbose_name="Instructor"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Malayalam", "Malayalam")],
                        max_length=100,
                    ),
                ),
                ("platform", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("event", models.CharField(max_length=128, null=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=120, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="meta"),
                ),
            ],
            options={
                "verbose_name": "Meta Tag",
                "verbose_name_plural": "Meta Tags",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("logo", models.ImageField(upload_to="partner")),
            ],
            options={
                "verbose_name": "Hiring Partner",
                "verbose_name_plural": "Hiring Partners",
            },
        ),
        migrations.CreateModel(
            name="Subscribtion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Team/", verbose_name="Team"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(null=True, unique=True)),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=128, null=True)),
                ("message", models.TextField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch_course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("course_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="course/"),
                ),
                ("details", models.TextField()),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("seat", models.IntegerField()),
                ("duration", models.CharField(max_length=10)),
                ("fees", models.CharField(max_length=50)),
                (
                    "syllabus",
                    models.FileField(blank=True, null=True, upload_to="syllabus"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=128, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch_course",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Branch_course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("place", models.CharField(max_length=128, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Branch_course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoursePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Coursepoints",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="reviewer")),
                ("review", models.TextField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
        ),
    ]
