# Generated by Django 4.2.7 on 2025-02-26 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_head", models.CharField(max_length=50)),
                ("banner_head_en", models.CharField(max_length=50, null=True)),
                ("banner_head_ml", models.CharField(max_length=50, null=True)),
                ("image", models.ImageField(upload_to="banner")),
                ("title", models.CharField(max_length=500)),
                ("title_en", models.CharField(max_length=500, null=True)),
                ("title_ml", models.CharField(max_length=500, null=True)),
                ("content", tinymce.models.HTMLField()),
                ("content_en", tinymce.models.HTMLField(null=True)),
                ("content_ml", tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_en", models.CharField(max_length=500, null=True)),
                ("title_ml", models.CharField(max_length=500, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("date", models.DateField()),
                ("person_name", models.CharField(max_length=50)),
                ("person_name_en", models.CharField(max_length=50, null=True)),
                ("person_name_ml", models.CharField(max_length=50, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="blog/", verbose_name="Blog"
                    ),
                ),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_en", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_ml", tinymce.models.HTMLField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("branch_name", models.CharField(max_length=300)),
                ("branch_name_en", models.CharField(max_length=300, null=True)),
                ("branch_name_ml", models.CharField(max_length=300, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("location", models.TextField()),
                ("location_en", models.TextField(null=True)),
                ("location_ml", models.TextField(null=True)),
                ("phone_number", models.CharField(max_length=100)),
                ("whatsapp_number", models.CharField(max_length=100)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="branch/"),
                ),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_en", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_ml", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "about_branch",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="About Branch"
                    ),
                ),
                (
                    "about_branch_en",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="About Branch"
                    ),
                ),
                (
                    "about_branch_ml",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="About Branch"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Branches",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_en", models.CharField(max_length=500, null=True)),
                ("title_ml", models.CharField(max_length=500, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("branch", models.CharField(max_length=100)),
                ("branch_en", models.CharField(max_length=100, null=True)),
                ("branch_ml", models.CharField(max_length=100, null=True)),
                ("date", models.DateField()),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_en", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_ml", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("position", models.CharField(max_length=128, null=True)),
                ("resume", models.FileField(max_length=500, upload_to="resume")),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="certificates/image")),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("order", models.PositiveIntegerField(null=True, unique=True)),
                ("course_name", models.CharField(max_length=100)),
                ("course_name_en", models.CharField(max_length=100, null=True)),
                ("course_name_ml", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="course/", verbose_name="Course"
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("details_en", models.TextField(blank=True, null=True)),
                ("details_ml", models.TextField(blank=True, null=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_en", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_ml", tinymce.models.HTMLField(blank=True, null=True)),
                ("seat", models.IntegerField()),
                ("duration", models.CharField(max_length=100)),
                ("duration_en", models.CharField(max_length=100, null=True)),
                ("duration_ml", models.CharField(max_length=100, null=True)),
                ("fees", models.CharField(max_length=50)),
                ("fees_en", models.CharField(max_length=50, null=True)),
                ("fees_ml", models.CharField(max_length=50, null=True)),
                (
                    "syllabus",
                    models.FileField(blank=True, null=True, upload_to="syllabus"),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        default="Offline",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("keyword", models.TextField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=155, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=165, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Endorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=128)),
                ("media", models.FileField(max_length=500, upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_ml", models.CharField(max_length=100, null=True)),
                ("venue", models.CharField(max_length=100)),
                ("venue_en", models.CharField(max_length=100, null=True)),
                ("venue_ml", models.CharField(max_length=100, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="freecourse/"
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("details", models.TextField()),
                ("details_en", models.TextField(null=True)),
                ("details_ml", models.TextField(null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Malayalam", "Malayalam")],
                        max_length=100,
                    ),
                ),
                ("platform", models.CharField(max_length=100)),
                ("platform_en", models.CharField(max_length=100, null=True)),
                ("platform_ml", models.CharField(max_length=100, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("question_en", models.CharField(max_length=500, null=True)),
                ("question_ml", models.CharField(max_length=500, null=True)),
                ("answer", models.TextField()),
                ("answer_en", models.TextField(null=True)),
                ("answer_ml", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("image", models.FileField(upload_to="gallery/image")),
            ],
            options={
                "verbose_name": "Galery",
                "verbose_name_plural": "Galeries",
            },
        ),
        migrations.CreateModel(
            name="IndexFooterGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="index_footer_gallery")),
            ],
            options={
                "verbose_name": "Index Footer Gallery",
                "verbose_name_plural": "Index Footer Gallery",
            },
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=120, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="meta"),
                ),
            ],
            options={
                "verbose_name": "Meta Tag",
                "verbose_name_plural": "Meta Tags",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128, null=True)),
                ("name_ml", models.CharField(max_length=128, null=True)),
                ("logo", models.ImageField(upload_to="partner")),
            ],
            options={
                "verbose_name": "Hiring Partner",
                "verbose_name_plural": "Hiring Partners",
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=128)),
                ("place", models.CharField(max_length=128)),
                ("image", models.FileField(upload_to="placed-students/image")),
            ],
            options={
                "verbose_name": "Placement",
                "verbose_name_plural": "Placements",
            },
        ),
        migrations.CreateModel(
            name="Subscribtion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Team/", verbose_name="Team"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_ml", models.CharField(max_length=50, null=True)),
                ("designation", models.CharField(max_length=200)),
                ("designation_en", models.CharField(max_length=200, null=True)),
                ("designation_ml", models.CharField(max_length=200, null=True)),
                ("order", models.PositiveIntegerField(null=True, unique=True)),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=50)),
                ("person_name_en", models.CharField(max_length=50, null=True)),
                ("person_name_ml", models.CharField(max_length=50, null=True)),
                ("designation", models.CharField(max_length=200)),
                ("designation_en", models.CharField(max_length=200, null=True)),
                ("designation_ml", models.CharField(max_length=200, null=True)),
                ("photo", models.ImageField(upload_to="reviewer")),
                ("review", models.TextField()),
                ("review_en", models.TextField(null=True)),
                ("review_ml", models.TextField(null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCourse",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, null=True)),
                ("course_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("image", models.TextField(max_length=100, verbose_name="Course")),
                ("details", models.TextField(blank=True, null=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("seat", models.IntegerField()),
                ("duration", models.CharField(max_length=100)),
                ("fees", models.CharField(max_length=50)),
                ("syllabus", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        default="Offline",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("keyword", models.TextField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=155, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=165, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical course",
                "verbose_name_plural": "historical courses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CoursePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("content_en", models.CharField(max_length=200, null=True)),
                ("content_ml", models.CharField(max_length=200, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Coursepoints",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("place", models.CharField(max_length=128, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Branch_course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=128, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch_course",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Branch_course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=128, null=True)),
                ("message", models.TextField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch_course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="story/", verbose_name="story"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Story",
                "verbose_name_plural": "Branch story",
            },
        ),
        migrations.CreateModel(
            name="BranchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text=" The recommended size is 800x600 pixels.",
                        upload_to="products/",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=120, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("course_name", models.CharField(max_length=100)),
                ("course_name_en", models.CharField(max_length=100, null=True)),
                ("course_name_ml", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="course/"),
                ),
                ("details", models.TextField()),
                ("details_en", models.TextField(null=True)),
                ("details_ml", models.TextField(null=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_en", tinymce.models.HTMLField(blank=True, null=True)),
                ("description_ml", tinymce.models.HTMLField(blank=True, null=True)),
                ("seat", models.IntegerField()),
                ("duration", models.CharField(max_length=10)),
                ("duration_en", models.CharField(max_length=10, null=True)),
                ("duration_ml", models.CharField(max_length=10, null=True)),
                ("fees", models.CharField(max_length=50)),
                ("fees_en", models.CharField(max_length=50, null=True)),
                ("fees_ml", models.CharField(max_length=50, null=True)),
                (
                    "syllabus",
                    models.FileField(blank=True, null=True, upload_to="syllabus"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
    ]
