# Generated by Django 5.0.1 on 2024-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="summary",
            field=models.TextField(
                default="We are looking for an enthusiastic and knowledgeable Digital Marketing Faculty member to join our educational team. The ideal candidate will have at least one year of experience in the digital marketing field and will be responsible for teaching courses based on our provided syllabus"
            ),
            preserve_default=False,
        ),
    ]
