# Generated by Django 5.0.1 on 2024-03-13 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventRegistration",
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
    ]
