# Generated by Django 5.0.1 on 2024-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_remove_careerapplication_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Offline",
                max_length=128,
                null=True,
            ),
        ),
    ]
