# Generated by Django 5.0.1 on 2024-06-23 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_course_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="details",
        ),
    ]
