# Generated by Django 5.0.1 on 2024-06-25 07:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_remove_course_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="banner_head_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="banner_head_ml",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="content_en",
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="content_ml",
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_ml",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="description_en",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="description_ml",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="person_name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="person_name_ml",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="title_ml",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="about_branch_en",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="About Branch"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="about_branch_ml",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="About Branch"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_name_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_name_ml",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="description_en",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="description_ml",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="location_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="location_ml",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="course_name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="course_name_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="description_en",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="description_ml",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="details_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="details_ml",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="duration_en",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="duration_ml",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="fees_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="branchcourse",
            name="fees_ml",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="branch_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="branch_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="description_en",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="description_ml",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="title_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="title_ml",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_name_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ml",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_en",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_ml",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="fees_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="fees_ml",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="coursepoint",
            name="content_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="coursepoint",
            name="content_ml",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="endorsement",
            name="designation_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="endorsement",
            name="designation_ml",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="endorsement",
            name="name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="endorsement",
            name="name_ml",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="details_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="details_ml",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="platform_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="platform_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ml",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ml",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_ml",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="designation_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="designation_ml",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="name_ml",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="designation_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="designation_ml",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="person_name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="person_name_ml",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="review_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="review_ml",
            field=models.TextField(null=True),
        ),
    ]
