# Generated by Django 5.0.1 on 2024-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_banner_banner_head_en_banner_banner_head_ml_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="certificates/image")),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=128)),
                ("place", models.CharField(max_length=128)),
                ("image", models.FileField(upload_to="placed-students/image")),
            ],
            options={
                "verbose_name": "Placement",
                "verbose_name_plural": "Placements",
            },
        ),
    ]
