# Generated by Django 5.0.1 on 2024-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_certification_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="meta_title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
