# Generated by Django 5.0.1 on 2024-09-01 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_blog_meta_description_blog_meta_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Endorsement",
        ),
    ]
