# Generated by Django 5.0.1 on 2024-03-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("duration", models.IntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Malayalam", "Malayalam")],
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "educational_qualification",
                    models.CharField(
                        choices=[
                            ("High School", "High School"),
                            ("SSLC", "SSLC"),
                            ("Higher Secondary", "Higher Secondary"),
                            ("Diploma", "Diploma"),
                            ("Bachelors Degree", "Bachelors Degree"),
                            ("Honours degree", "Honours degree"),
                            ("Post Graduate Degree", "Post Graduate Degree"),
                            ("Doctorate", "Doctorate"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.examination",
                        verbose_name="Examination",
                    ),
                ),
            ],
        ),
    ]
