# Generated by Django 5.0.1 on 2025-02-25 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_ml", models.CharField(max_length=100, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("duration", models.IntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[("English", "English"), ("Malayalam", "Malayalam")],
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_marks", models.IntegerField(default=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("educational_qualification", models.CharField(max_length=100)),
                ("mark", models.IntegerField(default=0)),
                (
                    "hallticket_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.examination",
                        verbose_name="Examination",
                    ),
                ),
            ],
        ),
    ]
