# Generated by Django 5.0.1 on 2024-03-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="mark",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examination",
            name="stage",
            field=models.CharField(
                choices=[
                    ("APPLICATION", "Accepting Applications"),
                    ("HALLTICKET", "Hall Ticket Published"),
                    ("EXAM", "Exam in Progress"),
                    ("RESULTS", "Results Published"),
                ],
                default="EXAM",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examination",
            name="total_marks",
            field=models.IntegerField(default=100),
        ),
    ]
