# Generated by Django 5.0.1 on 2024-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_application_mark_examination_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="hallticket_id",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
    ]
