# Generated by Django 5.0.1 on 2024-03-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_application_hallticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="stage",
            field=models.CharField(
                choices=[
                    ("APPLICATION", "Accepting Applications"),
                    ("HALLTICKET", "Hall Ticket Published"),
                    ("CLOSED", "Application Closed"),
                    ("WILL_PUBLISH", "Will Publish Results"),
                    ("RESULTS", "Results Published"),
                ],
                max_length=50,
            ),
        ),
    ]
