# Generated by Django 5.0.1 on 2024-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_alter_examination_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examination",
            name="stage",
        ),
        migrations.AlterField(
            model_name="application",
            name="educational_qualification",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="hallticket_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
