# Generated by Django 5.0.1 on 2024-06-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_remove_examination_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="examination",
            name="title_ml",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
